---
title: "Trabalho de Ciência de Dados para Economistas"
author: 
  - Matheus Canhete 
  - Felipe Paiva
  - Karina Reis
date: "`r format(Sys.time(), '%d %B %Y')`"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
biblio-style: apalike
link-citations: yes
---

# Título do Trabalho

## Configurar o ambiente de trabalho no R

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(require(rio))
suppressMessages(require(tidyverse))
library(pipeR)
library(DT)
suppressMessages(require(kableExtra))
suppressMessages(require(printr))

#setwd("/media/HD1TB/Pesquisa/PNAD_2015/Dados")
# instalar todos os formatos do pacote rio
# install_formats() 
```

Aqui é o espaćo para inserir texto.

__negrito__

_itálico_

## Importar o dados e transformá-los em `rds`

```{r echo=T, eval=F}

####################################
#### PRIMEIRA PARTE - load PNAD ####
####################################

# setwd("C:/Users/karin/OneDrive/Economia - UFMT/7º SEMESTRE/Ciência de Dados/pnad 2015")


#load("../PNAD/2015/Leitura_em_R_20170517dicPNAD2015")

# problema com a UF pela posição inicial, dropar as UF
#dicpes2015 <- dicpes2015[dicpes2015$cod2 != "UF",]

# ler os dados da pnad 2015 sem UF
#pnad2015 <- read.fwf("PES2015.txt", 
#                     widths = dicpes2015$tamanho2, 
#                     col.names = dicpes2015$cod2)

# criar a variavel UF 
#pnad2015$uf <- substr(pnad2015$V0102, 1, 2) 

# somente as pessoas com menos de 15 anos
#pnad2015_15 <- pnad2015[pnad2015$V8005 <= 15, ] 

# média de idade
#mean(pnad2015_15$V8005)

# que idade começou a trabalhar
#table(pnad2015_15$V9892)

# trabalho no período
#table(pnad2015_15$V0701)

# condição ocupação 
#table(pnad2015_15$V4805)

# ensino que frequenta
#table(pnad2015_15$V6003)

# mudar para Rds
#export(pnad2015, "pnad2015.rds")

#######################################################
#### EDUCAÇÃO DA PESSOA DE REFERÊNCIA NO DOMICÍLIO ####
#######################################################

pnad2015 <- import("../PNAD/2015/pnad2015.Rds")

vars <- c("uf", "V0102", "V0103", "V0301", "V0302", "V8005", "V0401", 
          "V0404", "V4011", "V0701", "V0704", "V7122", "V7128", "V0713",
          "V9001", "V9005", "V9029", "V9532", "V9058", "V9067", "V9971", "V9891", 
          "V9892", "V1272", "V1273", "V4801", "V4805", "V4809", "V4810", "V4812",
          "V4718", "V4728", "V4729", "V4742", "V4746", "V0403", "V6007", "V6003")

pnad2015_merged <- pnad2015 %>%                 # objeto principal 
  dplyr::filter(V0401 == 1) %>%              # filtrando apenas as pessoas de referencia  
  group_by(V0102, V0103, V0403) %>%             # agrupando por domicilio (numero de controle, serie e familia)
  summarise(educacao_pref = max(V6007)) %>%   # cria uma variavel com a educação da pessoa de ref
  ungroup() %>%                               # transforma o objeto novamente em um "dataframe" normal
  right_join(.,pnad2015 %>% select(vars))      # fusiona os dois dataframes selecionando apenas as variaveis desejadas da pnad2015

pnad2015_merged %>% dim()

# exporta dataframe como RDs
#export(pnad2015_merged, "pnad2015_pref.rds")

import("./2015/pnad2015_pref.Rds")

#############################
#### NÚMERO DE IRMÃOS #######
#############################

# importa o ultimo dataset ja com a variavel educacao_pref
pnad2015_merged <- import("pnad2015_pref.rds")

pnad_broder <- pnad2015_merged %>%      # dataframe principal
  subset(V0401 == 3) %>%                # seleciona apenas pessoas que sao filhos
  group_by(V0102, V0103, V0403) %>%     # agrupa por domicilio 
  summarise(filhos_domicilio = n()) %>% # cria uma variavel filhos_domicilio com numero de filhos no domicilio
  ungroup() %>%                         # desagrupa
  right_join(.,pnad2015_merged) %>%     # junta os dois dataframes (o agrupado com variavel filho e o da pnad)
  mutate(., nmr_irmaos =  if_else(V0401 == 3 & filhos_domicilio > 1, filhos_domicilio - 1, 0, missing = NaN))

# numero de irmãos
pnad_broder$nmr_irmaos %>% table()

# número médio de filhos por domicílio
pnad_broder$filhos_domicilio %>% mean(na.rm = T)

##################
#### EXPORTAR ####
##################

# subset apenas dos dados que serão usados no artigo (crianças de 5 a 15 anos)
pnadbroder_15 <- pnad_broder %>% subset(5 <= V8005 & V8005 <= 15)

#export(pnadbroder_15, "./2015/pes_5_15.Rds")

# cleaning up
#rm(list = ls());gc()
```


## CRIANDO AS TABELAS

```{r, message=F,warning=F,error=F}

pnad2015 <- import("./2015/pes_5_15.Rds")
pnad2015 %>% dim() 

# tabela 1 - percentual por ramo de atividade, idade, sexo
# tabela 2 - horas trabalhadas por ramo de atividade, idade, sexo

pnad2015_selected <- pnad2015 %>% select(V8005, V0302, V4746, V0713, V4812,
                                         V4805, V9001, V9058, V4809)  
# V8005 = idade
# V0302 = sexo
# V4746 = situacao ocupacao 5 anos ou mais
# V0713 = numero de horas trabalhadas
# V4812 = atividade crianças maiores de 5
# V4805 = condição ocupação 10 anos ou mais
# V9001 = trabalhou na semana
# V9058 = numero de horas habitualmente trabalhada
# V4809 = grupos atividade principal 

pt1.tabela1 <- pnad2015_selected %>%
  dplyr::filter(V4746 == 1 & V8005 <= 10) %>% # filtrando as crianças ocupadas de 5 a 10
  group_by(V4809, V0302) %>% # atividade desempenhada
  summarise(percental_5_10 = n()/nrow(.)*100) %>%
  ungroup()

pt2.tabela1 <- pnad2015_selected %>%
  dplyr::filter(V4746 == 1 & V8005 >= 11 & V8005 <= 15) %>% # filtrando as crianças ocupadas de 11 a 15
  group_by(V4809, V0302) %>% # atividade desempenhada
  summarise(percental_11_15 = n()/nrow(.)*100) %>%
  ungroup()

pt3.tabela1 <- pnad2015_selected %>%
  dplyr::filter(V4746 == 1) %>% # filtrando as crianças ocupadas de 5 a 15
  group_by(V4809, V0302) %>% # atividade desempenhada
  summarise(percental_5_15 = n()/nrow(.)*100) %>%
  ungroup()

tabela1 <- right_join(pt1.tabela1, pt2.tabela1) %>%  # merge das três partes
  right_join(., pt3.tabela1) %>%
  rename(atividade = V4809, sexo = V0302) 

# troca os valores por strings 
tabela1$sexo <- if_else(tabela1$sexo == 2, "masculino", "feminino")

tabela1$atividade <- factor(tabela1$atividade, levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                            labels = c("Agrícola", "Outras atividades industriais", "Indústria de transformação", "Construção", "Comércio e reparação",
                                       "Alojamento", "Transporte", "Administração pública", "Serviços sociais", "Serviços doméstico", "Outros serviços coletivos",
                                       "Outras atividades", "Atividades maldefinidas"))
# head(tabela1)

# tabela1 %>>% print(n=Inf)

#datatable(tabela1)
tabela1 %>>% 
  (kable(.,'html', col.names = c("A","S", "percentual 5 a 10", "perce", "ajksdj"), digits = 2)) %>>% 
  kable_styling() %>>% 
  scroll_box(width = "100%", height = "100%")


pt1.tabela2 <- pnad2015_selected %>%
  dplyr::filter(V4746 == 1 & V8005 <= 10) %>% # filtrando as crianças ocupadas de 5 a 10
  group_by(V4809) %>% # atividade desempenhada
  summarise(horas_trabalhadas_5_10 = mean(V9058)) %>%
  ungroup()

pt2.tabela2 <- pnad2015_selected %>%
  dplyr::filter(V4746 == 1 & V8005 >= 11 & V8005 <= 15) %>% # filtrando as crianças ocupadas de 11 a 15
  group_by(V4809) %>% # atividade desempenhada
  summarise(horas_trabalhadas_11_15 = mean(V9058)) %>%
  ungroup()

pt3.tabela2 <- pnad2015_selected %>%
  dplyr::filter(V4746 == 1) %>% # filtrando as crianças ocupadas de 5 a 15
  group_by(V4809) %>% # atividade desempenhada
  summarise(horas_trabalhadas_5_15 = mean(V9058)) %>%
  ungroup()

tabela2 <- right_join(pt1.tabela2, pt2.tabela2) %>%  # merge das três partes
  right_join(., pt3.tabela2) %>%
  rename(atividade = V4809) 

# troca os valores por strings 

tabela2$atividade <- factor(tabela2$atividade, levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                            labels = c("Agrícola", "Outras atividades industriais", "Indústria de transformação", "Construção", "Comércio e reparação",
                                       "Alojamento", "Transporte", "Administração pública", "Serviços sociais", "Serviços doméstico", "Outros serviços coletivos",
                                       "Outras atividades", "Atividades maldefinidas"))

tabela2 %>>% 
    datatable(extensions = 'Buttons', rownames=F,
              options = list(dom = 'Bfrtip', pageLength = 25,
                             buttons = list(list( 
                                                 extend='collection', 
                                                 buttons = list(list(extend='csv',filename='data'),
                                                                list(extend='excel',filename='data')),
                                                 text='Download'
                                                ))))

```

# TODO

- melhorar as tabelas
  - apresentar apenas duas casa decimais
  - melhorar os nomes das colunas
  
